### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by supriya-gdptl** [GostInShell/PaRI-Conv#2]
Hi @GostInShell ,
Thank you for sharing the code.
I am getting following error during training on last batch (4920 /4921) of first epoch
Could you take a look at the code and help me resolve the error? 
Appreciate your help

```
para_num is: 1.849128 MB
CosineAnnealingLR

[0: 4920/4921] train loss:  3.0886149406433105 Ellapsed Time: 0.07949230167600844h ETL: 23.775468789989244h

Traceback (most recent call last):
  File "train.py", line 44, in <module>
    main()
  File "train.py", line 23, in main
    trainer.train_epoch()
  File "PaRI-Conv/trainer.py", line 192, in train_epoch
    self.train_iteration()
  File "PaRI-Conv/trainer.py", line 175, in train_iteration
    pred = self.network(self.data)
  File "/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "PaRI-Conv/Networks/model.py", line 194, in forward
    x = F.leaky_relu(self.bn6(self.linear1(x)), negative_slope=0.2)
  File "python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "python3.7/site-packages/torch/nn/modules/batchnorm.py", line 179, in forward
    self.eps,
  File "python3.7/site-packages/torch/nn/functional.py", line 2280, in batch_norm
    _verify_batch_size(input.size())
  File "python3.7/site-packages/torch/nn/functional.py", line 2248, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512])

```
Thank you,
Supriya

**Comment by GostInShell** [comment]
I'm terribly sorry for the late reply. (Maybe it's time to subscribe the notification. :( ) 

I could not reproduce the error. But a quick guess is inappropriate batch size. You should set `batch size > 1`. If it's not the case, maybe try setting `drop_last=True` [here](https://github.com/GostInShell/PaRI-Conv/blob/7479f8b44b3f2593848dfcb35e93b0661411ac6f/trainer.py#L106).

Sorry again. Feel free to raise other concerns.

**Comment by supriya-gdptl** [comment]
Thank you for the reply.
The solution you suggested solved my problem.
I was using `batch_size` of 2.
Now I changed it to 8 as well as set `drop_last=True` in `DataLoader` on [L106](https://github.com/GostInShell/PaRI-Conv/blob/7479f8b44b3f2593848dfcb35e93b0661411ac6f/trainer.py#L106) and [L112](https://github.com/GostInShell/PaRI-Conv/blob/7479f8b44b3f2593848dfcb35e93b0661411ac6f/trainer.py#L112) in `trainer.py`.
The code is now running without any errors.

Thank you,
Supriya
